import { readFileSync, readdirSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The admin subscribes to the topics the API publishes, and to no others.
 *
 * `api/contract/mercure-topics.json` is generated by the API's
 * MercureTopicContractTest from `Maggie\Core\Mercure\MercureTopic`. Reading
 * the file rather than restating its contents is the point: a resource
 * renamed on the server fails here, in the same pull request, instead of on a
 * screen that quietly stops refreshing.
 *
 * Silence is the whole problem. An EventSource pointed at a topic nobody
 * publishes connects, stays open and delivers nothing — there is no error to
 * notice and no log to read.
 */

// Matches both the resource-relative form the call sites are meant to use and
// the user-scoped form they must not: the pre-scoped check below is only worth
// making if a pre-scoped literal can actually be matched.
const TOPIC_LITERAL = /'((?:\/users\/[^']*)?\/api\/[a-z_]+\/\{id\})'/g

/**
 * The contract directory, wherever this suite happens to be running from: the
 * checkout under CI, or `task wt:test:admin`, which mounts admin/ as /app and
 * the contract as /api/contract. Walking up covers both without either
 * needing to know about the other.
 */
function contractDir(): string {
  let candidate = resolve(process.cwd())
  for (;;) {
    const contract = join(candidate, 'api', 'contract')
    try {
      statSync(contract)
      return contract
    } catch {
      const parent = dirname(candidate)
      if (parent === candidate) break
      candidate = parent
    }
  }
  throw new Error(
    `No api/contract/ directory found above ${process.cwd()}. ` +
      'The API suite generates it: UPDATE_CONTRACT=1 task wt:test:api -- --testsuite Contract',
  )
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) return sourceFiles(full)
    return /\.tsx?$/.test(entry.name) && !/\.(test|spec)\.tsx?$/.test(entry.name) ? [full] : []
  })
}

describe('the admin Mercure subscriptions', () => {
  // Vitest runs from admin/, so the sources are simply src/.
  const adminSrc = resolve(process.cwd(), 'src')
  const published: Record<string, string> = JSON.parse(
    readFileSync(join(contractDir(), 'mercure-topics.json'), 'utf8'),
  )

  // The contract stores the full subscribed pattern; useMercure is given the
  // resource part and prefixes the scope itself, so compare on that part.
  const publishedResourceTopics = new Set(
    Object.values(published).map((pattern) => pattern.replace('/users/{userId}', '')),
  )

  const subscribed = sourceFiles(adminSrc).flatMap((file) =>
    [...readFileSync(file, 'utf8').matchAll(TOPIC_LITERAL)].map((match) => ({
      file: file.slice(adminSrc.length + 1),
      topic: match[1],
    })),
  )

  it('finds the topic literals it is meant to check', () => {
    // Without this the suite would pass by matching nothing, the day someone
    // moves the *_TOPICS constants or changes their quoting.
    expect(subscribed.length).toBeGreaterThan(5)
  })

  it('only subscribes to topics the API publishes', () => {
    const unpublished = subscribed.filter(({ topic }) => !publishedResourceTopics.has(topic))

    expect(
      unpublished,
      `These subscriptions name a topic the API does not publish, so they will never fire:\n` +
        unpublished.map(({ file, topic }) => `  ${file}: ${topic}`).join('\n') +
        `\nPublished: ${[...publishedResourceTopics].sort().join(', ')}`,
    ).toEqual([])
  })

  it('scopes every topic to the current user', () => {
    // The scope lives in useMercure alone; the call sites pass the resource
    // part. A literal that already carries /users/ has bypassed the hook.
    const preScoped = subscribed.filter(({ topic }) => topic.startsWith('/users/'))

    expect(preScoped, 'A call site builds the user scope itself instead of leaving it to useMercure.').toEqual([])

    expect(
      readFileSync(join(adminSrc, 'hooks', 'useMercure.ts'), 'utf8'),
      'useMercure no longer prefixes its topics with the user scope; every subscription in the admin would go silent.',
    ).toContain('`/users/${userId}${topic}`')
  })

  it('opens every EventSource with credentials', () => {
    // Updates are private: the hub delivers them only to a request carrying
    // the mercureAuthorization cookie, which the browser sends cross-origin
    // only with withCredentials (MAG-139).
    const withoutCredentials = sourceFiles(adminSrc).filter((file) =>
      [...readFileSync(file, 'utf8').matchAll(/new EventSource\([^\n]*\)/g)].some(
        (match) => !/withCredentials:\s*true/.test(match[0]),
      ),
    )

    expect(
      withoutCredentials.map((file) => file.slice(adminSrc.length + 1)),
      'These files open an EventSource without withCredentials: a private update never reaches them.',
    ).toEqual([])
  })
})
