import { readFileSync, readdirSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The admin sends no query parameter the API has not declared.
 *
 * The mobile counterpart of this test found `accountId` on
 * MaggieApiService.getTransactions. The admin had the same defect, in
 * AccountTransactionsView, and nothing on this side would have caught it:
 * the only admin contract test covered Mercure topics.
 *
 * Both defects worked in production, which is why they lasted. API Platform
 * drops a parameter it does not declare, but the Elasticsearch translator
 * turned any unrecognised string into a term query and the transaction index
 * happens to hold a field called `accountId` — so the list narrowed until the
 * provider fell back to Doctrine, and then quietly showed every account's
 * transactions.
 *
 * `openapi.json` is the oracle: it is generated by the API suite and lists
 * every parameter each path declares. A path absent from it is not an API
 * Platform collection — the finance panels and the search bar call custom
 * controllers, which parse their own query string.
 */

/**
 * React Admin's Hydra data provider turns `sort: { field, order }` into
 * `order[field]` and `filter: { k: v }` into `k=v`. Both are read here, from
 * the source, because what has to be checked is the string — a call through
 * a mocked provider would only prove the admin sends what the admin sends.
 */
const SORT_FIELD = /sort:\s*\{\s*field:\s*'([^']+)'/g
const FILTER_KEYS = /filter(?::|=\{)\s*\{\{?([^}]*)\}/g
const FILTER_KEY = /'?([A-Za-z0-9_[\]]+)'?\s*:/g

/** React Admin supplies these itself; no entity declares them. */
const PAGINATION = new Set(['page', 'itemsPerPage'])

function repositoryRoot(): string {
  let candidate = resolve(process.cwd())
  for (;;) {
    try {
      statSync(join(candidate, 'api', 'contract'))
      return candidate
    } catch {
      const parent = dirname(candidate)
      if (parent === candidate) break
      candidate = parent
    }
  }
  throw new Error(
    `No api/contract/ directory found above ${process.cwd()}. ` +
      'The API suite generates it: UPDATE_CONTRACT=1 task wt:test:api -- --testsuite Contract',
  )
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) return sourceFiles(full)
    return /\.tsx?$/.test(entry.name) && !/\.(test|spec)\.tsx?$/.test(entry.name) ? [full] : []
  })
}

/** Collection path → the parameters the API declares for its GET. */
function declaredParameters(root: string): Map<string, Set<string>> {
  const document = JSON.parse(readFileSync(join(root, 'api', 'contract', 'openapi.json'), 'utf8'))
  const declared = new Map<string, Set<string>>()

  for (const [path, operations] of Object.entries(document.paths as Record<string, Record<string, unknown>>)) {
    const get = operations.get as { parameters?: { name: string }[] } | undefined
    if (!get) continue
    declared.set(path, new Set((get.parameters ?? []).map((p) => p.name)))
  }

  return declared
}

/**
 * Every parameter name the admin puts on the wire, whatever the resource.
 *
 * Resource attribution is deliberately not attempted: `getList('tasks', …)`
 * and `<List resource="transactions" filter={…}>` name their resource three
 * lines away from the parameter, and a regex that guessed wrong would either
 * miss a defect or block a pull request over nothing. Checking each name
 * against the union of everything the API declares is weaker — `order[name]`
 * sent to `/api/tasks` would pass because `/api/agendas` declares it — but it
 * is honest, and it catches the whole class this test exists for: a name the
 * API knows nowhere at all.
 */
function parametersSent(adminSrc: string): { file: string; parameter: string }[] {
  return sourceFiles(adminSrc).flatMap((file) => {
    const source = readFileSync(file, 'utf8')
    const relative = file.slice(adminSrc.length + 1)

    const sorts = [...source.matchAll(SORT_FIELD)].map((match) => ({
      file: relative,
      parameter: `order[${match[1]}]`,
    }))

    const filters = [...source.matchAll(FILTER_KEYS)].flatMap((block) =>
      [...block[1].matchAll(FILTER_KEY)].map((key) => ({ file: relative, parameter: key[1] })),
    )

    return [...sorts, ...filters].filter(({ parameter }) => !PAGINATION.has(parameter))
  })
}

describe('the admin query parameters', () => {
  const root = repositoryRoot()
  const adminSrc = resolve(process.cwd(), 'src')
  const declared = declaredParameters(root)
  const everyDeclaredName = new Set([...declared.values()].flatMap((names) => [...names]))
  const sent = parametersSent(adminSrc)

  it('finds the parameters it is meant to check', () => {
    // Without this the suite passes by matching nothing, the day the call
    // sites change shape.
    expect(sent.length).toBeGreaterThan(8)
    expect(sent.map((s) => s.parameter)).toContain('exists[completedAt]')
  })

  it('sends nothing the API declares nowhere', () => {
    const unknown = sent.filter(({ parameter }) => !everyDeclaredName.has(parameter))

    expect(
      unknown,
      'These query parameters are declared by no API resource, so API Platform drops them and the collection comes ' +
        'back unfiltered — no error, no log, just the wrong list on screen:\n' +
        unknown.map(({ file, parameter }) => `  ${file}: ${parameter}`).join('\n') +
        '\nDeclare each with an #[ApiFilter] on the entity, and add it to api/contract/query-parameters.json.',
    ).toEqual([])
  })

  it('sends nothing missing from the published client contract', () => {
    const contract: Record<string, Record<string, string>> = JSON.parse(
      readFileSync(join(root, 'api', 'contract', 'query-parameters.json'), 'utf8'),
    )
    const listed = new Set(Object.values(contract).flatMap((params) => Object.keys(params)))

    const unlisted = sent.filter(({ parameter }) => !listed.has(parameter))

    expect(
      unlisted,
      'These parameters are declared by the API but missing from api/contract/query-parameters.json, so nothing on ' +
        'the API side proves they still narrow anything:\n' +
        unlisted.map(({ file, parameter }) => `  ${file}: ${parameter}`).join('\n'),
    ).toEqual([])
  })
})
