package com.maggie.app.data.fcm

import android.app.NotificationManager
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * The channels the app creates are the channels the server names.
 *
 * `api/contract/push-channels.json` is written by the API's PushChannelContractTest from
 * `PushMessageFactory`. A message sent to a channel the phone never created is shown without
 * sound or importance, and nothing fails on either side. No channel per notification type.
 */
@RunWith(AndroidJUnit4::class)
class PushChannelsContractTest {

    private val published: List<String> by lazy {
        val file = generateSequence(File("").absoluteFile) { it.parentFile }
            .map { File(it, "api/contract/push-channels.json") }
            .firstOrNull { it.isFile }
        assertNotNull(
            "api/contract/push-channels.json is missing. It is generated by the API suite: " +
                "UPDATE_CONTRACT=1 task wt:test:api -- --testsuite Contract",
            file,
        )
        Json.parseToJsonElement(file!!.readText()).jsonArray.map { it.jsonPrimitive.content }
    }

    @Test
    fun `the app declares exactly the channels the server names`() {
        assertEquals(published.sorted(), PushChannels.ALL.sorted())
    }

    @Test
    fun `every published channel exists on the phone once the app has started`() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        PushChannels.create(context)

        val manager = context.getSystemService(NotificationManager::class.java)
        published.forEach { id ->
            assertTrue("The channel \"$id\" is named by the server and not created", manager.getNotificationChannel(id) != null)
        }
        assertEquals(published.size, manager.notificationChannels.size)
    }
}
