framework:
    messenger:
        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - 'Maggie\Calendar\Middleware\MercurePublishMiddleware'
                    - 'Maggie\Core\Elasticsearch\Middleware\ElasticsearchIndexMiddleware'

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'Maggie\Calendar\Message\CreateEventCommand': sync
            'Maggie\Calendar\Message\UpdateEventCommand': sync
            'Maggie\Calendar\Message\DeleteEventCommand': sync
            'Maggie\Calendar\Message\CreateAgendaCommand': sync
            'Maggie\Calendar\Message\UpdateAgendaCommand': sync
            'Maggie\Calendar\Message\DeleteAgendaCommand': sync
            'Maggie\Calendar\Message\CreateTaskCommand': sync
            'Maggie\Calendar\Message\UpdateTaskCommand': sync
            'Maggie\Calendar\Message\DeleteTaskCommand': sync
            'Maggie\Calendar\Message\PushEventToGoogleCommand': sync
            'Maggie\Calendar\Message\DeleteEventFromGoogleCommand': sync
            'Maggie\Calendar\Message\PullFromGoogleCommand': async
            'Maggie\Calendar\Message\PushTaskToGoogleCommand': sync
            'Maggie\Calendar\Message\DeleteTaskFromGoogleCommand': sync
            'Maggie\Calendar\Message\PullTasksFromGoogleCommand': async
            'Maggie\Core\Message\UpdateUserCommand': sync
            'Maggie\Core\Message\UpdateUserPreferenceCommand': sync
            'Maggie\Notification\Message\CreateNotificationCommand': sync
            'Maggie\Notification\Message\MarkNotificationReadCommand': sync
            'Maggie\Notification\Message\DeleteNotificationCommand': sync
            'Maggie\Cookbook\Message\CreateProductCommand': sync
            'Maggie\Cookbook\Message\UpdateProductCommand': sync
            'Maggie\Cookbook\Message\DeleteProductCommand': sync
            'Maggie\Cookbook\Message\CreateIngredientCommand': sync
            'Maggie\Cookbook\Message\UpdateIngredientCommand': sync
            'Maggie\Cookbook\Message\DeleteIngredientCommand': sync
            'Maggie\Cookbook\Message\CreateRecipeCommand': sync
            'Maggie\Cookbook\Message\UpdateRecipeCommand': sync
            'Maggie\Cookbook\Message\DeleteRecipeCommand': sync
            'Maggie\Cookbook\Message\CreateMealCommand': sync
            'Maggie\Cookbook\Message\UpdateMealCommand': sync
            'Maggie\Cookbook\Message\DeleteMealCommand': sync
            'Maggie\Cookbook\Message\CreateGroceryListCommand': sync
            'Maggie\Cookbook\Message\UpdateGroceryListCommand': sync
            'Maggie\Cookbook\Message\DeleteGroceryListCommand': sync
            'Maggie\Cookbook\Message\GenerateGroceryListCommand': sync
            'Maggie\Cookbook\Message\AddGroceryItemCommand': sync
            'Maggie\Cookbook\Message\CheckGroceryItemCommand': sync
            'Maggie\Cookbook\Message\CreateRecurringGroceryItemCommand': sync
            'Maggie\Cookbook\Message\UpdateRecurringGroceryItemCommand': sync
            'Maggie\Cookbook\Message\DeleteRecurringGroceryItemCommand': sync
            'Maggie\Core\Elasticsearch\Message\IndexDocumentCommand': async
            'Maggie\Core\Elasticsearch\Message\DeleteDocumentCommand': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
