security:
    providers:
        app_user_provider:
            entity:
                class: Maggie\Core\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        auth:
            pattern: ^/api/auth
            stateless: true
            security: false
        google_webhook:
            pattern: ^/api/calendar/google/webhook
            stateless: true
            security: false
        token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/token/refresh
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/calendar/google/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: ROLE_USER }
