services:
    _defaults:
        autowire: true
        autoconfigure: true

    Maggie\Proaction\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/MaggieProactionBundle.php'

    Maggie\Proaction\Service\AgentHubClient:
        arguments:
            $agentHubUrl: '%env(AGENT_HUB_URL)%'
