services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            string $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            string $googleRedirectUri: '%env(GOOGLE_REDIRECT_URI)%'
            string $adminUrl: '%env(ADMIN_URL)%'

    Maggie\Core\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Trait/'
            - '../src/MaggieCoreBundle.php'

    Elastic\Elasticsearch\Client:
        factory: ['Maggie\Core\Elasticsearch\ElasticsearchClientFactory', 'create']
        arguments:
            $elasticsearchUrl: '%env(ELASTICSEARCH_URL)%'

    Maggie\Core\Elasticsearch\State\ElasticsearchCollectionProvider:
        arguments:
            $doctrineProvider: '@ApiPlatform\Doctrine\Orm\State\CollectionProvider'
            $environment: '%kernel.environment%'

    Maggie\Core\Elasticsearch\State\ElasticsearchItemProvider:
        arguments:
            $doctrineProvider: '@ApiPlatform\Doctrine\Orm\State\ItemProvider'

    Maggie\Core\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
