services:
    _defaults:
        autowire: true
        autoconfigure: true

    Maggie\Finance\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/MaggieFinanceBundle.php'
