#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Maggie K3s rollback (MAG-106)
# Usage: scripts/rollback-k3s.sh
#
# Run by the CD workflow when a deploy or its post-deploy smoke suite fails.
# Puts back, with `kubectl rollout undo`, every deployment whose revision
# changed since deploy-k3s.sh recorded them — and only those: one the deploy did
# not touch has no new revision, and undoing it would send it to an older
# release than the one it serves.
#
# What it does NOT undo: database migrations and Elasticsearch mappings. The
# deploy takes a pg_dump first; its path is printed so the owner can restore it
# if the failure needs it.
# =============================================================================

NAMESPACE="maggie"
STATE_DIR="${MAGGIE_STATE_DIR:-/opt/maggie/state}"
REVISIONS_FILE="$STATE_DIR/pre-deploy-revisions"
BACKUP_DIR="${MAGGIE_BACKUP_DIR:-/opt/maggie/backups}"
KUBECTL="${KUBECTL:-sudo k3s kubectl}"

log()  { echo "==> $*"; }
warn() { echo "WARNING: $*" >&2; }

if [ ! -s "$REVISIONS_FILE" ]; then
  log "No pre-deploy revisions recorded: the deploy never reached the apply phase, nothing to roll back."
  exit 0
fi

failed=0
rolled_back=0

while read -r deploy revision <&3; do
  current=$($KUBECTL get "deployment/$deploy" -n "$NAMESPACE" \
    -o jsonpath='{.metadata.annotations.deployment\.kubernetes\.io/revision}' 2>/dev/null || true)

  if [ -z "$current" ]; then
    warn "$deploy no longer exists — skipped"
    continue
  fi

  if [ "$current" = "$revision" ]; then
    log "$deploy untouched by this deploy (revision $revision) — left as is"
    continue
  fi

  log "$deploy: revision $current → back to $revision"
  if $KUBECTL rollout undo "deployment/$deploy" -n "$NAMESPACE" --to-revision="$revision" \
    && $KUBECTL rollout status "deployment/$deploy" -n "$NAMESPACE" --timeout=180s; then
    rolled_back=$((rolled_back + 1))
  else
    warn "$deploy did not come back on revision $revision"
    failed=1
  fi
done 3< "$REVISIONS_FILE"

# A run that restored everything consumes the record, so a second one cannot
# undo twice. After a failure it stays, so the rollback can be run again.
if [ "$failed" -eq 0 ]; then
  rm -f "$REVISIONS_FILE"
fi

log "Rolled back $rolled_back deployment(s)."
warn "Migrations and Elasticsearch mappings were NOT reverted."
# shellcheck disable=SC2012 # names are generated by deploy-k3s.sh, plain ASCII
latest_backup=$(ls -1t "$BACKUP_DIR"/maggie_predeploy_*.sql.gz 2>/dev/null | head -1 || true)
if [ -n "$latest_backup" ]; then
  warn "Database dump taken before the deploy: $latest_backup"
fi

$KUBECTL get pods -n "$NAMESPACE"

exit "$failed"
