apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciqual
  namespace: maggie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciqual
  template:
    metadata:
      labels:
        app: ciqual
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: ciqual
          image: ghcr.io/miwi35/maggie-ciqual:latest
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /ciqual/docs
              port: 8002
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 200m
