services:
    _defaults:
        autowire: true
        autoconfigure: true

    Maggie\Cookbook\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/MaggieCookbookBundle.php'

    Maggie\Cookbook\Service\CiqualClient:
        arguments:
            $ciqualServiceUrl: '%env(CIQUAL_SERVICE_URL)%'

    Maggie\Cookbook\EventListener\MealDiscriminatorListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    Maggie\Cookbook\EventListener\IngredientDiscriminatorListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
