services:
    _defaults:
        autowire: true
        autoconfigure: true

    Maggie\Cookbook\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/MaggieCookbookBundle.php'

    Maggie\Cookbook\EventListener\MealDiscriminatorListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
