package com.maggie.app.data.mercure

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The app subscribes to the topics the API publishes, and to no others.
 *
 * `api/contract/mercure-topics.json` is written by the API's
 * MercureTopicContractTest from `Maggie\Core\Mercure\MercureTopic`, the single
 * place that spells a topic on the server. This test reads that file — the
 * same bytes the API committed — so the two sides are compared rather than
 * both believed.
 *
 * It is worth the file-reading because the failure it prevents is completely
 * silent. A Mercure subscription to a topic nobody publishes connects, stays
 * connected, reconnects when dropped, and never delivers an event. Two of the
 * app's subscriptions were in that state when this test was written:
 * GroceryViewModel passed the literal `{userId}` MercureService never
 * substitutes, and RecipeListViewModel left out the `/users/{userId}` scope
 * entirely.
 */
class MercureTopicsContractTest {

    private val contract: Map<String, String> by lazy {
        val file = contractFile("mercure-topics.json")
        Json.parseToJsonElement(file.readText())
            .let { it as kotlinx.serialization.json.JsonObject }
            .mapValues { (_, value) -> value.jsonPrimitive.content }
    }

    @Test
    fun `every collection the app subscribes to is published by the API`() {
        val published = contract.values.toSet()

        MercureTopics.SUBSCRIBED.forEach { collection ->
            val topic = MercureTopics.userScoped("{userId}", collection)

            assertTrue(
                "The app subscribes to \"$topic\", which the API does not publish.\n" +
                    "Nothing will fail at runtime: the SSE connection opens and simply never delivers an event.\n" +
                    "Published topics: ${published.sorted().joinToString("\n  ", prefix = "\n  ")}",
                published.contains(topic),
            )
        }
    }

    @Test
    fun `the topic builder produces the API's convention verbatim`() {
        // Spelled out rather than derived, so a change to userScoped() that
        // happens to keep matching the contract file still has to be read by
        // somebody.
        assertEquals(
            "/users/01HXYZ/api/grocery_lists/{id}",
            MercureTopics.userScoped("01HXYZ", MercureTopics.GROCERY_LISTS),
        )
    }

    /**
     * The half that catches a new subscription written by hand.
     *
     * MercureTopics is only a contract if everything goes through it; a
     * ViewModel that builds its own string is exactly how the two dead
     * subscriptions got in. Topics outside the API's namespace — the agent's
     * `/chat/…` and `/contexts/…` — are not this contract's business and are
     * skipped.
     */
    @Test
    fun `no ViewModel builds an api topic by hand`() {
        val subscriptions = sourceRoot().walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .flatMap { file ->
                Regex("""mercureService\.subscribe\(([^)]*)\)""")
                    .findAll(file.readText())
                    .map { file.name to it.groupValues[1].trim() }
            }
            .toList()

        // Without this the test passes on nothing the day subscribe() moves
        // behind a helper, which is how the two dead subscriptions it was
        // written for would come back.
        assertTrue(
            "Found no mercureService.subscribe call at all, so this test checked nothing.",
            subscriptions.size >= 8,
        )

        val offenders = subscriptions.filter { (_, argument) -> argument.contains("/api/") }

        assertTrue(
            "These subscriptions build an API topic from a literal instead of going through MercureTopics, " +
                "so nothing checks them against the API's contract:\n" +
                offenders.joinToString("\n") { (file, argument) -> "  $file: $argument" },
            offenders.isEmpty(),
        )
    }

    private fun sourceRoot(): File {
        val root = repositoryRoot()
        return File(root, "mobile/app/src/main/java").also {
            assertTrue("Cannot find the mobile sources at ${it.absolutePath}", it.isDirectory)
        }
    }

    private fun contractFile(name: String): File =
        File(repositoryRoot(), "api/contract/$name").also {
            assertTrue(
                "The API contract file ${it.absolutePath} is missing. " +
                    "It is generated by the API suite: UPDATE_CONTRACT=1 task wt:test:api -- --testsuite Contract",
                it.isFile,
            )
        }

    /**
     * Walks up from the working directory — Gradle runs unit tests from
     * mobile/app — until it finds the checkout. Resolving by relative depth
     * would break the day the module moves.
     */
    private fun repositoryRoot(): File {
        var candidate: File? = File("").absoluteFile
        while (candidate != null) {
            if (File(candidate, "api/contract").isDirectory) return candidate
            candidate = candidate.parentFile
        }
        throw AssertionError("No directory containing api/contract/ found above ${File("").absolutePath}")
    }
}
