services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            string $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            string $googleWebhookUrl: '%env(GOOGLE_WEBHOOK_URL)%'
            string $googleWebhookToken: '%env(GOOGLE_WEBHOOK_TOKEN)%'

    Maggie\Calendar\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Dto/'
            - '../src/Trait/'
            - '../src/MaggieCalendarBundle.php'
