services:
    _defaults:
        autowire: true
        autoconfigure: true

    Maggie\Calendar\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/MaggieCalendarBundle.php'
