<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

// migrations/ is generated by Doctrine and never edited by hand, so it stays as generated.
$finder = (new Finder())
    ->in([
        __DIR__.'/config',
        __DIR__.'/modules',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    ->name('*.php')
    ->exclude(['var', 'vendor']);

return (new Config())
    ->setRules(['@Symfony' => true])
    ->setFinder($finder);
